apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mails
spec:
  volumeName: nfs-mails
  #storageClassName: nfs-data-sc
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi

