apiVersion: v1
kind: Service
metadata:
  name: nfs
  labels:
    app: nfs-server
spec:
  # type: LoadBalancer
  # NOTE: for NFS, a headless service is recommended:
  clusterIP: None
  selector:
    run: nfs-server
    # app: nfs-server
  ports:
  - name: rpcbind
    protocol: TCP
    port: 111
    targetPort: 111
  - name: rpcbind-udp
    protocol: UDP
    port: 111
    targetPort: 111
  - name: nfs
    protocol: TCP
    port: 2049
    targetPort: 2049
  - name: nfs-udp
    protocol: UDP
    port: 2049
    targetPort: 2049
  - name: mountd
    protocol: TCP
    port: 20048
    targetPort: 20048
  - name: mountd-udp
    protocol: UDP
    port: 20048
    targetPort: 20048
  # - name: statd
  #   protocol: TCP
  #   port: 32765
  #   targetPort: 32765
  # - name: statd-udp
  #   protocol: UDP
  #   port: 32765
  #   targetPort: 32765
  # - name: nlockmgr
  #   protocol: TCP
  #   port: 32803
  #   targetPort: 32803
  # - name: nlockmgr-udp
  #   protocol: UDP
  #   port: 32803
  #   targetPort: 32803

