apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dmarc-dev

##labels:
##- pairs:
##    app: haraka
##  #includeSelectors: true
##  #includeTemplates: true
#
##namePrefix: haraka-
#
#generatorOptions:
#  disableNameSuffixHash: true

#configMapGenerator:
#- name: haraka-config
#  behavior: merge
#  files:
#  - files/host_list
#  - files/me
#  #- files/file-provider.yml

patches:
# replace file:
#- path: ingress.yml

# strategic merge patching:
#- patch: |-
#    apiVersion: networking.k8s.io/v1
#    kind: Ingress
#    metadata:
#      name: nginx-to-traefik
#    spec:
#      rules:
#      - host: 'auth.mydmarc.csr-informatik.de'
#      - host: 'mydmarc.csr-informatik.de'

# json 6902 patching:
- target:
    kind: Deployment
    name: dmarc-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: europe-west3-docker.pkg.dev/csrinternal/mail-analytics/dmarc-app:latest
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
- target:
    kind: ConfigMap
    name: dmarc-app-config
  patch: |-
    - op: replace
      path: /data/PHX_HOST
      value: dev.mydmarc.csr-informatik.de
- target:
    kind: Ingress
    name: dmarc-app
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        cert-manager.io/issuer: "letsencrypt-staging"
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - dev.mydmarc.csr-informatik.de
        - mydmarc.csr-informatik.de
        secretName: mydmarc.csr-informatik.de-tls
    - op: replace
      path: /spec/rules/0/host
      value: dev.mydmarc.csr-informatik.de
#    - op: remove
#      path: /spec/rules/0
#    - op: add
#      path: /spec/rules/0
#      value:
#        host: 'dev.mydmarc.csr-informatik.de'
#        http:
#          paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: dmarc-app
#                port:
#                  name: http

