[package]
name = "mail-analytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
libsqlite3-sys = "0.28.0"
tokio = { version = "1.36.0", features = ["full"] }
xml-rs = "0.8.19"
