# NOTE: we're not using ceph atm

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmarc-app-filestorage
  labels:
    app: dmarc-app
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
