apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yml
- serviceaccount.yml
- clusterrolebinding.yml
#- configmap.yml
- deployment.yml
- service.yml

namespace: traefik

labels:
- pairs:
    app: traefik

#namePrefix: haraka-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: traefik-config
  files:
  - files/traefik.yml
  - files/file-provider.yml


