apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yml
- secret.yml
- statefulset.yml
- service.yml

namespace: dmarc-dev

labels:
- pairs:
    app: postgres

#namePrefix: haraka-

#generatorOptions:
#  disableNameSuffixHash: true
#
#configMapGenerator:
#- name: haraka-file-config
#  files:
#  - files/host_list
#  - files/internalcmd_key
#  - files/log.ini
#  - files/loglevel
#  - files/me
#  - files/plugins
#  - files/quarantine.ini
#  - files/rabbitmq.ini
#  - files/smtp.ini
#  - files/smtpgreeting
#  - files/ehlo_hello_message
#  - files/connection_close_message

