apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  #type: LoadBalancer
  clusterIP: None  # headless service for statefulset
  selector:
    run: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
