apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  labels:
    app: traefik
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
        asDefault: true
      #websecure:
        #address: ":443"
    
    providers:
      kubernetesIngress:
        namespaces:
        - "dmarc-dev"
      #file:
        #filename: '/etc/traefik/file-provider.yml'
    
    api:
      insecure: true

  file-provider.yml: |
    http:
      # Add the router
      routers:
        router0:
          entryPoints:
          - web
          #middlewares:
          #- my-basic-auth
          service: service-foo
          rule: Path(`/query`)
          #rule: Host(`localhost`)
    
      # Add the middleware
      #middlewares:
      #  my-basic-auth:
      #    basicAuth:
      #      users:
      #      - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
      #      - test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0
      #      usersFile: etc/traefik/.htpasswd
    
      # Add the service
      services:
        service-foo:
          loadBalancer:
            servers:
              - url: http://host.containers.internal:8081
            passHostHeader: false

