apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  labels:
    app: traefik
spec:
  #type: LoadBalancer
  type: ClusterIP
  #clusterIP: None  # headless service for statefulset
  selector:
    app: traefik
  ports:
  - name: traefik-dashboard
    port: 8080
    targetPort: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web
  labels:
    app: traefik
spec:
  type: LoadBalancer
  #clusterIP: None  # headless service for statefulset
  selector:
    app: traefik
  ports:
  - name: traefik-web
    port: 80
    targetPort: web
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-websecure
  labels:
    app: traefik
spec:
  type: LoadBalancer
  #clusterIP: None  # headless service for statefulset
  selector:
    app: traefik
  ports:
  - name: traefik-websecure
    port: 443
    targetPort: websecure

