apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- configmap.yml
- deployment.yml
- service.yml
- ingress.yml

namespace: traefik

#labels:
#- pairs:
#    app: traefik
#  #includeSelectors: true
#  #includeTemplates: true

#namePrefix: haraka-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: authelia-config
  files:
  - files/configuration.yml
  - files/users_database.yml

