entryPoints:
  web:
    address: ":80"
    asDefault: true
  websecure:
    address: ":443"

providers:
  #docker:
  #  defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    filename: '/etc/traefik/file-provider.yml'

api:
  insecure: true

