apiVersion: v1
kind: Service
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  type: LoadBalancer
  selector:
    run: nfs
  ports:
  - name: nfs
    protocol: TCP
    port: 2049
    targetPort: 2049
  - name: mountd
    protocol: TCP
    port: 32767
    targetPort: 32767
  #- name: mountd
  #  protocol: TCP
  #  port: 20048
  #  targetPort: 20048
  #- name: rpcbind
  #  protocol: TCP
  #  port: 111
  #  targetPort: 111

