apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- pvc.yml
- configmap.yml
- deployment.yml
- service.yml
- ingress.yml
  #- secret.yml # NOTE: don't include secret.yml here, as that may overwrite deployed secrets unintentionally

namespace: dmarc-dev

labels:
- pairs:
    app: dmarc-app

#namePrefix: haraka-

#generatorOptions:
#  disableNameSuffixHash: true
#
#configMapGenerator:
#- name: haraka-config
#  files:
#  - files/host_list
#  - files/internalcmd_key
#  - files/log.ini
#  - files/loglevel
#  - files/me
#  - files/plugins
#  - files/quarantine.ini
#  - files/rabbitmq.ini
#  - files/smtp.ini
#  - files/smtpgreeting
#  - files/ehlo_hello_message
#  - files/connection_close_message

