log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    asDefault: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true
  smtp:
    address: ":25"
    asDefault: false

providers:
  kubernetesCRD:
    namespaces:
    - "traefik"
    - "dmarc-dev"
    labelSelector: 'router=traefik'
  kubernetesIngress:
    namespaces:
    - "traefik"
    - "dmarc-dev"
    labelSelector: 'router=traefik'
  file:
    filename: '/etc/traefik/file-provider.yml'

api:
  insecure: true

