apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

#namespace: traefik

##labels:
##- pairs:
##    app: traefik
##  #includeSelectors: true
##  #includeTemplates: true
#
##namePrefix: haraka-
#
#generatorOptions:
#  disableNameSuffixHash: true

configMapGenerator:
- name: traefik-config
  behavior: merge
  files:
  - files/traefik.yml
  #- files/file-provider.yml

patches:
# replace file:
#- path: ingress.yml

# strategic merge patching:
#- patch: |-
#    apiVersion: networking.k8s.io/v1
#    kind: Ingress
#    metadata:
#      name: nginx-to-traefik
#    spec:
#      rules:
#      - host: 'auth.mydmarc.csr-informatik.de'
#      - host: 'mydmarc.csr-informatik.de'

# json 6902 patching:
- target:
    kind: Ingress
    name: nginx-to-traefik
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: 'auth.mydmarc.csr-informatik.de'
    - op: replace
      path: /spec/rules/1/host
      value: 'mydmarc.csr-informatik.de'

